app/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers

router = routers.DefaultRouter()
router.register('products', views.ProductViewset, basename='products')
router.register('bids', views.BidViewset, basename='bids')
router.register('users', views.UserViewset, basename='users')

urlpatterns = [
    path('', views.home, name='home'),
    path('section/<str:type>', views.section, name='section'),
    path('product/<int:id>', views.product, name='product'),
    path('sale/', views.sale, name='sale'),
    path('profile/', views.profile, name='profile'),
    path('login/', views.login_signin, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('api/', include(router.urls)),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

""" 
Represents each product on the db 
"""
class Product(models.Model):
    MEASURES = (
        ('units', 'Units'),
        ('kg', 'Kilograms'),
        ('l', 'Liters'),
    )

    TYPES = (
        ('clock', 'Clock auctions'),
        ('dutch', 'Dutch auctions'),
        ('sealed', 'Sealed bid auctions'),
    )

    title = models.CharField(max_length=200)
    description = models.TextField()
    quantity = models.DecimalField(max_digits=8, decimal_places=2)
    measure = models.CharField(max_length=30, choices=MEASURES)
    type = models.CharField(max_length=30, choices=TYPES)
    initial_bid = models.DecimalField(max_digits=8, decimal_places=2)
    final_bid = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    origin = models.CharField(max_length=30)
    created_date = models.DateTimeField(default=timezone.now)
    finished_date = models.DateTimeField()

    winner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='winner', blank=True, null=True)
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='seller')

    def __str__(self):
        return self.title

""" 
Represents each bid on the db 
"""
class Bid(models.Model):
    price = models.DecimalField(max_digits=8, decimal_places=2)
    created_date = models.DateTimeField(default=timezone.now)

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    buyer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

""" 
Represents each product picture on the db 
"""
class Picture(models.Model):
    image = models.ImageField(upload_to='products')

    product = models.ForeignKey(Product, on_delete=models.CASCADE)

""" 
Add specific data to the user
"""
class Profile(models.Model):
    stars = models.DecimalField(max_digits=2, decimal_places=1, default=0)
    image = models.ImageField(upload_to='profiles', blank=True, null=True)
    
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie-edge">
    <title>4Sale</title>
    <link rel="shortcut icon" type="image/jpg" href="{% static 'media/favicon.png' %}"/>


    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <!-- FONTAWESOME -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <!-- OWN CSS -->
    {% block css%}
    {% endblock %}

</head>
<body>
    <header class="navbar navbar-expand-lg py-0 bd-navbar sticky-top">
        
        <a href="{% url 'home' %}"><img class="logo ms-5" src="{% static 'media/Logo.png' %}"></a>

        <button class="navbar-toggler me-5" type="button" data-bs-toggle="collapse" data-bs-target="#bdNavbar" aria-controls="bdNavbar" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>

        <div class="justify-content-between collapse navbar-collapse px-5 px-lg-0" id="bdNavbar">

            <div class="navbar-nav">
                <ul class="navbar-nav bd-navbar-nav flex-row flex-wrap text-center">
                    {% url 'section' 'clock' as url %}
                    <li class="nav-item col-4 col-lg-auto"><a href="{% url 'section' 'clock'%}" class="nav-link px-xxl-4 px-lg-3 {% if request.path == url or product.type == 'clock' %}selected{% endif %}">Clock auctions</a></li>
                    {% url 'section' 'dutch' as url %}
                    <li class="nav-item col-4 col-lg-auto"><a href="{% url 'section' 'dutch'%}" class="nav-link px-xxl-4 px-lg-3 {% if request.path == url or product.type == 'dutch' %}selected{% endif %}">Dutch auctions</a></li>
                    {% url 'section' 'sealed' as url %}
                    <li class="nav-item col-4 col-lg-auto"><a href="{% url 'section' 'sealed'%}" class="nav-link px-xxl-4 px-lg-3 {% if request.path == url or product.type == 'sealed' %}selected{% endif %}">Sealed bid auctions</a></li>
                </ul>
             </div>
                    
            <hr class="d-lg-none text-white-50">

            <div class="navbar-nav flex-row me-lg-5 text-center">
                <a href="{% url 'sale' %}" class="nav-item nav-link px-xxl-4 px-lg-2 col-4 col-lg-auto {% if request.resolver_match.url_name == 'sale' %}selected{% endif %}">Sale</a>
                <div class="input-group rounded m-auto mx-3">
                    <input type="search" class="form-control search" placeholder="Search..." aria-label="Search" aria-descrbedby="search"/>
                    <span class="input-group-text border-0" id="search"><i class="fas fa-search"></i></span>
                </div>
                {% if user.is_authenticated %}
                    <a href="{% url 'profile' %}" class="m-auto"><i class="fas fa-user m-auto px-lg-3"></i></a>
                {% else %}
                    <a href="{% url 'login' %}" class="m-auto"><i class="fas fa-sign-in-alt m-auto px-lg-3"></i></a>
                {% endif %}
            </div>

            <br class="d-lg-none">
        </div>
    </header>

    {% if messages %}
        {% for m in messages %}
            <div class="alert alert-{{m.tags}} d-flex align-items-center px-0" role="alert">
                <i class="{% if m.tags == 'success' %}fas fa-check-circle{% else %}fas fa-exclamation-circle{% endif %} h1 ms-5 me-2 mb-0"></i> {{m}}
            </div>
        {% endfor %}
    {% endif %}

    <!-- OWN VIEW -->
    {% block content %}
    {% endblock %}
    
    <!-- JQUERY -->
    <script src="https://code.jquery.com/jquery-3.6.0.slim.js" integrity="sha256-HwWONEZrpuoh951cQD1ov2HUK5zA5DwJ1DNUXaM6FsY=" crossorigin="anonymous"></script>
    
    <!-- BOOTSTRAP -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- SWEETALERT -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- JS -->
    <script src="{% static 'js/base.js' %}"></script>

    <!-- OWN JS -->
    {% block js%}
    {% endblock %}

</body>
</html>

app/templates/app/home.html
{% extends 'app/base.html' %}
{% load static %}

{% block css %}

    <link rel="stylesheet" href="{% static 'css/home.css' %}">

{% endblock %}

{% block content %}

    <main class="p-5 pb-0"> 
        <div>
            <h2>Clock auctions</h2>
            <div class="row row-cols-2 row-cols-sm-4 row-cols-lg-5 row-cols-xl-6">
                {% for product in clock_products %}
                    <a href="{% url 'product' product.id %}" {% if forloop.counter0 == 4 %}class="hide-xl"{% elif forloop.counter0 == 3 %}class="hide-lg"{% elif forloop.counter0 > 0 %}class="hide-sm"{% endif %}>
                        <figure>
                            <div class="image-container"><div class="image"><img class="d-block w-100" src="{{ product.picture_set.first.image.url }}"></div></div>
                        </figure>
                    </a>
                {% endfor %}
                <a href="{% url 'section' 'clock'%}" class="my-auto"><i class="fas fa-arrow-right"></i></a>
            </div>
        </div>

        <div class="mt-4">
            <h2>Dutch auctions</h2>
            <div class="row row-cols-2 row-cols-sm-3 row-cols-lg-4 row-cols-xl-6">
                {% for product in dutch_products %}
                    <a href="{% url 'product' product.id %}">
                        <figure>
                            <div class="image-container"><div class="image"><img class="d-block w-100" src="{{ product.picture_set.first.image.url }}"></div></div>
                        </figure>
                    </a>
                {% endfor %}
                <a href="{% url 'section' 'dutch'%}" class="my-auto"><i class="fas fa-arrow-right"></i></a>
            </div>            
        </div>

        <div class="mt-4">
            <h2>Sealed bid auctions</h2>
            <div class="row row-cols-2 row-cols-sm-3 row-cols-lg-4 row-cols-xl-6">
                {% for product in sealed_products %}
                    <a href="{% url 'product' product.id %}">
                        <figure>
                            <div class="image-container"><div class="image"><img class="d-block w-100" src="{{ product.picture_set.first.image.url }}"></div></div>
                        </figure>
                    </a>
                {% endfor %}
                <a href="{% url 'section' 'sealed'%}" class="my-auto"><i class="fas fa-arrow-right"></i></a>
            </div>            
        </div>
    </main>
    
{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block css %}

    <link rel="stylesheet" href="{% static 'css/login.css' %}">

{% endblock %}

{% block content %}

    <main class="p-5 pb-0">   
        <div class="container d-flex justify-content-center">
            <div class="card col-sm-9 col-xl-6 text-center">
                <ul class="nav nav-fill">
                    <li class="nav-item"><a id="login-link" class="nav-link {% if not signin %}active{% endif %}" data-bs-toggle="tab" href="#login">Log in</a></li>
                    <li class="nav-item"><a id="signin-link" class="nav-link {% if signin %}active{% endif %}" data-bs-toggle="tab" href="#signin">Sign in</a></li>
                </ul>

                <div class="px-5 py-4">                
                    <div class="tab-content">

                        <div id="login" class="tab-pane fade {% if not signin %}show active{% endif %}">
                            <h2 class="fw-bold mb-4">Log in</h2>
                            <form method="POST">
                                {% csrf_token %}

                                <div class="form-floating mb-4">
                                    <input type="text" id="username" name="username" class="form-control" {% if username %}value="{{username}}" {%endif%}placeholder="Username" required/>
                                    <label for="username">Username</label>
                                </div>
            
                                <div class="form-floating mb-4">
                                    <input type="password" id="password" name="password" class="form-control" {% if password %}value="{{password}}" {%endif%}placeholder="Password" required/>
                                    <label for="password">Password</label>
                                    {% if username %}<p class="text-start text-danger">Username and password does not match</p>{% endif %}
                                </div>
                
                                <button type="submit" class="btn btn-primary w-100 mb-4">Log in</button>
                
                                {% comment %} <div class="text-center">
                                    <p>or log in with:</p>
                                    <button type="button" class="btn mx-1"><i class="fab fa-facebook-f"></i></button>
                                    <button type="button" class="btn mx-1"><i class="fab fa-google"></i></button>
                                    <button type="button" class="btn mx-1"><i class="fab fa-twitter"></i></button>
                                    <button type="button" class="btn mx-1"><i class="fab fa-github"></i></button>
                                </div> {% endcomment %}
                            </form>
                        </div>            

                        <div id="signin" class="tab-pane fade {% if signin %}show active{% endif %}">            
                            <h2 class="fw-bold mb-4">Sign in</h2>
                            <form method="POST">
                                {% csrf_token %}

                                <div class="row">
                                    <div class="col-md-6 mb-4">
                                        <div class="form-floating">
                                            {% if oldForm %}{% render_field oldForm.first_name|attr:'required' class='form-control' placeholder="First Name" %}{% else %}{% render_field form.first_name|attr:'required' class='form-control' placeholder="First Name" %}{% endif %}
                                            <label for="first_name">First name</label>
                                        </div>
                                    </div>
                                                    
                                    <div class="col-md-6 mb-4">
                                        <div class="form-floating">
                                            {% if oldForm %}{% render_field oldForm.last_name|attr:'required' class='form-control' placeholder="Last name" %}{% else %}{% render_field form.last_name|attr:'required' class='form-control' placeholder="Last name" %}{% endif %}
                                            <label for="last_name">Last name</label>
                                        </div>
                                    </div>
                                </div>
                    
                                <div class="form-floating mb-4">
                                    {% if oldForm %}{% render_field oldForm.username class='form-control' placeholder="Username" %}{% else %}{% render_field form.username class='form-control' placeholder="Username" %}{% endif %}
                                    <label for="username">Username</label>
                                    {% if 'username' in oldForm.errors %}<p class="text-start text-danger mb-0">A user with that username already exists</p>{% endif %}
                                </div>
            
                                <div class="form-floating mb-4">
                                    {% if oldForm %}{% render_field oldForm.email|attr:'required' class='form-control' placeholder="name@gmail.com" %}{% else %}{% render_field form.email|attr:'required' class='form-control' placeholder="name@gmail.com" %}{% endif %}
                                    <label for="email">Email address</label>
                                    {% if 'email' in oldForm.errors %}<p class="text-start text-danger mb-0">Enter a valid email address</p>{% endif %}
                                </div>
                    
                                <div class="form-floating mb-4">
                                    {% if oldForm %}{% render_field oldForm.password1 class='form-control' type="password" placeholder="Password" %}{% else %}{% render_field form.password1 class='form-control' type="password" placeholder="Password" %}{% endif %}
                                    <label for="password1">Password</label>
                                    {% if 'password2' not in oldForm.errors or not oldForm %}
                                        <ul class="text-start">
                                            <li>It can’t be similar to your personal data</li>
                                            <li>It must contain at least 8 characters</li>
                                            <li>It can’t be a commonly used password</li>
                                            <li>It can’t be entirely numeric</li>
                                        </ul>
                                    {% endif %}
                                </div>

                                <div class="form-floating mb-4">
                                    {% if oldForm %}{% render_field oldForm.password2 class='form-control' type="password" placeholder="Password" %}{% else %}{% render_field form.password2 class='form-control' type="password" placeholder="Password" %}{% endif %}
                                    <label for="password2">Password confirmation</label>
                                    {% if 'password2' in oldForm.errors %} {% for error in oldForm.password2.errors %}<p class="text-start text-danger mb-0">{{error|escape}}</p>{% endfor %}{% endif %}
                                </div>
                                
                                <button type="submit" class="btn btn-primary w-100 mb-4">Sign in</button>
                
                                {% comment %} <div class="text-center">
                                    <p>or sign in with:</p>
                                    <button type="button" class="btn mx-1"><i class="fab fa-facebook-f"></i></button>
                                    <button type="button" class="btn mx-1"><i class="fab fa-google"></i></button>
                                    <button type="button" class="btn mx-1"><i class="fab fa-twitter"></i></button>
                                    <button type="button" class="btn mx-1"><i class="fab fa-github"></i></button>
                                </div> {% endcomment %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

app/templates/app/product.html
{% extends 'app/base.html' %}
{% load static %}
{% load mathfilters %}

{% block css %}

    <link rel="stylesheet" href="{% static 'css/product.css' %}">

{% endblock %}

{% block content %}
    <main class="p-5">
        <div class="d-md-flex justify-content-center">
            <div id="image" class="mx-auto mx-md-0 me-md-4">
                <div id="carousel" class="carousel slide" data-bs-interval="false" >
                    <div class="carousel-indicators">
                        {%for picture in product.picture_set.all %}
                            {% if product.picture_set.count != 1 %}<button type="button" data-bs-target="#carousel" data-bs-slide-to="{{forloop.counter0}}" {% if forloop.counter0 == 0 %} class="active" aria-current="true" {% endif %} aria-label="Slide {{forloop.counter0|add:"1"}}"></button> {% endif %}
                        {%endfor%}
                    </div>

                    <div class="carousel-inner">
                        {%for picture in product.picture_set.all %}
                            <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}">
                                <img src="{{picture.image.url}}" class="d-block w-100">
                            </div>
                        {%endfor%}
                    </div>

                    {% if product.picture_set.count != 1 %}
                        <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>

                        <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    {% endif %}
                </div>
            </div>

            <div>
                <h2>{{product.title}}</h2>
                <p>{{product.description}}</p>
    
                <h5 class="mb-3">{% if product.measure == 'units' %}{{product.quantity|floatformat}}{% else %}{{product.quantity}}{% endif %} {{product.measure}}</h5>
                
                <h6 class="d-none finished_date">{{product.finished_date|date:"M d, Y H:i:s" }}</h6>
                {% if not product.winner and product.type == 'dutch' or product.type != 'dutch' %}<h6 class="countdown"></h6>{% endif %}

                {% if product.type == 'dutch' and not product.winner %}
                    <h6 class="d-none created_date">{{product.created_date|date:"M d, Y H:i:s" }}</h6>
                    <h6 class="d-none initial_bid">{{product.initial_bid }}</h6>
                    <h6 class="d-none final_bid">{{product.final_bid }}</h6>             
                {% endif %}

                {% if product.type == 'clock' %}<h5>Current bid: {% if product.bid_set.count == 0 %}{{product.initial_bid}}{% else %}{{product.bid_set.last.price}}{% endif %}€</h5>{% endif %}
                
                {% if finished %}
                    <h6 class="mb-4" id="winner">{{product.winner}} win the bid for {{product.bid_set.last.price}}€</h6>
                {% elif user.is_authenticated %}
                    <div class="form-group mt-3 mt-md-0 mb-4">
                        <form class="d-flex" method="POST">
                            {% csrf_token %}
                            <div class="form-floating">        
                                <input type="number" class="form-control" id="price" name="price" {% if product.type != 'dutch' %} value="{% if product.bid_set.count != 0 and product.type == 'clock' %}{{product.bid_set.last.price|addition:"0.01"}}{% else %}{{product.initial_bid}}{% endif %}" min="{% if product.bid_set.count != 0 and product.type == 'clock' %}{{product.bid_set.last.price|addition:"0.01"}}{% else %}{{product.initial_bid}}{% endif %}" {% else %}readonly{% endif %} step=".01" required>
                                <label for="price">Price</label>
                            </div>
                            <button type="submit" class="btn btn-primary">Pay</button>
                        </form>
                    </div>
                {% else %}
                    <a href="{% url 'login' %}"><button class="btn btn-primary rounded mt-4 mt-md-0 mb-4">Login to bid</button></a>
                {% endif %}
                
                {% if product.type == 'clock' %}
                    {% if product.bid_set.count != 0 %}
                        <div class="bid m-auto mb-4 p-3 text-center">
                            <h5 class="mb-3">Bidding history</h5>
                            {%for bid in product.bid_set.all|dictsortreversed:"created_date"|slice:":5" %}                            
                                <div class="d-flex justify-content-between">
                                    <div class="me-md-4">{{bid.buyer}}</div>
                                    <div class="me-md-4">{{bid.created_date|date:"d/m/Y H:i:s"}}</div>
                                    <div>{{bid.price}}€</div>
                                </div>
                            {%endfor%}
                            {% if product.bid_set.count > 5 %}<p class="text-center mb-0">...</p>{% endif %}
                        </div>
                    {% endif %}                    
                {% endif %}
            </div>
        </div>

        <div class="d-flex m-auto" id="profile-container">
            {% if product.seller.profile.image %}
                <div id="profile" class="d-flex bg-transparent">
                    <img class="w-100 m-auto rounded-circle" src="{{ product.seller.profile.image.url }}"/>
                </div>
            {% else %}
                <div id="profile" class="d-flex align-items-center justify-content-center rounded-circle" >
                    <h1>{{ product.seller.first_name|slice:"1"|upper }}{{ product.seller.last_name|slice:"1"|upper }}</h1>
                </div>
            {% endif %}
            
            <div class="m-auto ms-4">
                <h5 class="mb-2 mb-sm-4">{{product.seller.get_full_name}}</h5>
                <div>
                    <i class="{% if product.seller.profile.stars == 0.5 %}fas fa-star-half-alt{% elif product.seller.profile.stars > 0.5 %}fas fa-star{% else %}far fa-star{% endif%}"></i>
                    <i class="{% if product.seller.profile.stars == 1.5 %}fas fa-star-half-alt{% elif product.seller.profile.stars > 1.5 %}fas fa-star{% else %}far fa-star{% endif%}"></i>
                    <i class="{% if product.seller.profile.stars == 2.5 %}fas fa-star-half-alt{% elif product.seller.profile.stars > 2.5 %}fas fa-star{% else %}far fa-star{% endif%}"></i>
                    <i class="{% if product.seller.profile.stars == 3.5 %}fas fa-star-half-alt{% elif product.seller.profile.stars > 3.5 %}fas fa-star{% else %}far fa-star{% endif%}"></i>
                    <i class="{% if product.seller.profile.stars == 4.5 %}fas fa-star-half-alt{% elif product.seller.profile.stars > 4.5 %}fas fa-star{% else %}far fa-star{% endif%}"></i>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

{% block js %}

    <script src="{% static 'js/product.js' %}"></script>

{% endblock %}

app/templates/app/section.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}

    <link rel="stylesheet" href="{% static 'css/section.css' %}">

{% endblock %}

{% block content %}
    <main class="p-5">        

        {% if products|length != 0 %}
            <div class="row row-cols-2 row-cols-sm-3 row-cols-lg-4 row-cols-xl-5">
                {% for product in products %}
                    <a href="{% url 'product' product.id %}">
                        <figure>
                            <div class="image-container"><div class="image"><img class="d-block w-100" src="{{ product.picture_set.first.image.url }}"></div></div>
                            <h2>{{ product.title }}</h2>
                            <h6 class="d-none finished_date">{{product.finished_date|date:"M d, Y H:i:s" }}</h6>
                            {% if product.type == 'dutch' %}
                                <h6 class="d-none created_date">{{product.created_date|date:"M d, Y H:i:s" }}</h6>
                                <h6 class="d-none initial_bid">{{product.initial_bid }}</h6>
                                <h6 class="d-none final_bid">{{product.final_bid }}</h6>
                            {% elif product.type == 'clock' %}
                                <h5>Current bid: {% if product.bid_set.count == 0 %}{{product.initial_bid}}{% else %}{{product.bid_set.last.price}}{% endif %}€</h5>
                            {% endif %}
                                <h6 class="countdown mb-4"></h6>
                        </figure>
                    </a>
                {% endfor %}
            </div>
        {% else %}
            <div class="text-center">
                <h1>There are no products on sale</h1>
            </div>
        {% endif %}
    </main>   
    
{% endblock %}

{% block js %}

    <script src="{% static 'js/section.js' %}"></script>

{% endblock %}